(function () {
  const status = document.querySelector('#course-status'); const courseForm = document.querySelector('#course-form'); const unitForm = document.querySelector('#unit-form'); const lessonForm = document.querySelector('#lesson-form'); const panel = document.querySelector('#authoring-panel'); const lessonPanel = document.querySelector('#lesson-panel'); const publish = document.querySelector('#publish-course'); let courseId = ''; let unitId = '';
  function signIn() { window.location.replace('index.html'); }
  function add(selector, text) { const item = document.createElement('li'); item.textContent = text; document.querySelector(selector).appendChild(item); }
  function call(action, data) { return window.LMS_API.call(action, data, true); }
  courseForm.addEventListener('submit', async function(event) { event.preventDefault(); if (!courseForm.reportValidity()) return; const button = courseForm.querySelector('button'); button.disabled = true; try { const v = new FormData(courseForm); const result = await call('COURSE_CREATE', { title: v.get('title'), description: v.get('description'), courseType: v.get('courseType'), academicYear: v.get('academicYear'), semester: v.get('semester') }); courseId = result.course.courseId; document.querySelector('#draft-title').textContent = result.course.title; panel.hidden = false; courseForm.hidden = true; status.textContent = 'สร้างรายวิชาแบบร่างแล้ว'; } catch (error) { status.textContent = error.message; } finally { button.disabled = false; } });
  unitForm.addEventListener('submit', async function(event) { event.preventDefault(); if (!unitForm.reportValidity()) return; const button = unitForm.querySelector('button'); button.disabled = true; try { const v = new FormData(unitForm); const unit = await call('COURSE_CREATE_UNIT', { courseId: courseId, title: v.get('title'), sortOrder: Number(v.get('sortOrder')) }); unitId = unit.unitId; document.querySelector('#selected-unit').textContent = unit.title; lessonPanel.hidden = false; add('#unit-list', unit.title); unitForm.reset(); status.textContent = 'เพิ่มหน่วยแล้ว'; } catch (error) { status.textContent = error.message; } finally { button.disabled = false; } });
  lessonForm.addEventListener('submit', async function(event) { event.preventDefault(); if (!lessonForm.reportValidity()) return; const button = lessonForm.querySelector('button'); button.disabled = true; try { const v = new FormData(lessonForm); const lesson = await call('COURSE_CREATE_LESSON', { unitId: unitId, title: v.get('title'), contentUrl: v.get('contentUrl'), sortOrder: Number(v.get('sortOrder')) }); add('#lesson-list', lesson.title); lessonForm.reset(); status.textContent = 'เพิ่มบทเรียนแล้ว'; } catch (error) { status.textContent = error.message; } finally { button.disabled = false; } });
  publish.addEventListener('click', async function() { publish.disabled = true; try { await call('COURSE_PUBLISH', { courseId: courseId }); status.textContent = 'เผยแพร่รายวิชาแล้ว'; publish.hidden = true; } catch (error) { status.textContent = error.message; publish.disabled = false; } });
  (async function() { if (!sessionStorage.getItem('lms_session_token')) return signIn(); try { const me = await call('ME', {}); if (me.permissions.indexOf('courses.create') === -1) window.location.replace('dashboard.html'); } catch (_) { signIn(); } }());
}());
