(function () {
  const status = document.querySelector('#formal-status'); const content = document.querySelector('#formal-content'); const select = document.querySelector('#formal-course'); const meta = document.querySelector('#course-meta'); let courses = [];
  function signIn() { window.location.replace('index.html'); }
  function call(action, fields) { return window.LMS_API.call(action, fields, true); }
  function selectedCourse() { return courses.find(function (course) { return course.courseId === select.value; }); }
  function renderCourse() { const course = selectedCourse(); meta.textContent = course ? [course.academicYear, 'ภาคเรียน ' + course.semester, course.status === 'PUBLISHED' ? 'เผยแพร่แล้ว' : 'ฉบับร่าง'].join(' | ') : ''; }
  function submit(form, action, fields, success) { form.addEventListener('submit', async function (event) { event.preventDefault(); if (!form.reportValidity() || !select.value) return; const button = form.querySelector('button'); button.disabled = true; status.textContent = ''; try { const result = await call(action, Object.assign({ courseId: select.value }, fields(new FormData(form)))); status.textContent = success(result); status.dataset.state = 'success'; form.reset(); } catch (error) { status.textContent = error.message; status.dataset.state = ''; } finally { button.disabled = false; } }); }
  async function load() { if (!sessionStorage.getItem('lms_session_token')) return signIn(); try { const me = await call('ME', {}); if (me.permissions.indexOf('courses.publish') === -1) return window.location.replace('dashboard.html'); const data = await call('COURSE_LIST_MANAGED_FORMAL', {}); courses = data.courses; select.replaceChildren(); if (!courses.length) { status.textContent = 'ยังไม่มีรายวิชาในภาคเรียน โปรดสร้างรายวิชาแบบ “วิชาในภาคเรียน” ก่อน'; return; } courses.forEach(function (course) { const option = document.createElement('option'); option.value = course.courseId; option.textContent = course.title + ' (' + course.academicYear + '/' + course.semester + ')'; select.appendChild(option); }); renderCourse(); content.hidden = false; } catch (error) { if (error.code === 'UNAUTHENTICATED') return signIn(); status.textContent = error.message; } }
  select.addEventListener('change', renderCourse);
  submit(document.querySelector('#staff-form'), 'COURSE_ASSIGN_STAFF', function (form) { return { username: form.get('username'), staffRole: form.get('staffRole') }; }, function (result) { return result.assignmentStatus === 'ALREADY_ASSIGNED' ? 'ครูคนนี้ถูกกำหนดในรายวิชาแล้ว' : 'กำหนดครูประจำวิชาเรียบร้อย'; });
  submit(document.querySelector('#enrollment-form'), 'COURSE_ASSIGN_FORMAL_ENROLLMENT', function (form) { return { username: form.get('username') }; }, function (result) { return result.enrollmentStatus === 'ALREADY_ENROLLED' ? 'นักเรียนคนนี้อยู่ในรายวิชาแล้ว' : 'เพิ่มนักเรียนเข้าเรียนเรียบร้อย'; });
  load();
}());
