(function () {
  const status = document.querySelector('#learn-status'); const courses = document.querySelector('#learning-courses'); const outline = document.querySelector('#outline');
  function signIn() { window.location.replace('index.html'); }
  function call(action, data) { return window.LMS_API.call(action, data, true); }
  function card(course) { const node = document.createElement('article'); node.className = 'course-card'; const title = document.createElement('h3'); title.textContent = course.title; const description = document.createElement('p'); description.className = 'course-card__description'; description.textContent = course.description || 'พร้อมเริ่มเรียน'; const button = document.createElement('button'); button.className = 'primary-button'; button.textContent = 'เปิดรายวิชา'; button.addEventListener('click', function () { openCourse(course.courseId); }); node.append(title, description, button); return node; }
  function contentBlock(block) { const node = document.createElement('div'); node.className = 'lesson-content-block'; if (block.body) { const body = document.createElement('p'); body.textContent = block.body; node.appendChild(body); } if (block.mediaUrl) { const link = document.createElement('a'); link.href = block.mediaUrl; link.target = '_blank'; link.rel = 'noopener'; link.textContent = 'เปิด' + ({ VIDEO: 'วิดีโอ', AUDIO: 'เสียง', PDF: 'เอกสาร PDF', IMAGE: 'รูปภาพ', LINK: 'ลิงก์' }[block.contentType] || 'สื่อ'); node.appendChild(link); } return node; }
  async function openCourse(courseId) { try { const data = await call('COURSE_LEARNING_OUTLINE', { courseId: courseId }); courses.hidden = true; outline.hidden = false; document.querySelector('#outline-title').textContent = data.course.title; const units = document.querySelector('#unit-outline'); units.replaceChildren(); data.units.forEach(function (unit) { const section = document.createElement('section'); section.className = 'account-panel'; const title = document.createElement('h3'); title.textContent = unit.title; section.appendChild(title); unit.lessons.forEach(function (lesson) { const lessonNode = document.createElement('article'); const label = document.createElement('h4'); label.textContent = lesson.title + (lesson.completed ? ' (เรียนจบแล้ว)' : ''); lessonNode.appendChild(label); if (lesson.contentUrl) lessonNode.appendChild(contentBlock({ contentType: 'LINK', mediaUrl: lesson.contentUrl })); lesson.contentBlocks.forEach(function (block) { lessonNode.appendChild(contentBlock(block)); }); if (lesson.lessonId === 'lesson_ai_k230_1_1') { const practice = document.createElement('a'); practice.href = 'ai-ml-dl.html'; practice.className = 'secondary-button'; practice.textContent = 'ฝึกดูความสัมพันธ์ AI, ML และ DL'; lessonNode.appendChild(practice); } const complete = document.createElement('button'); complete.className = 'secondary-button'; complete.textContent = lesson.completed ? 'เรียนจบแล้ว' : 'ทำเครื่องหมายว่าเรียนจบ'; complete.disabled = lesson.completed; complete.addEventListener('click', async function () { try { await call('LESSON_COMPLETE', { lessonId: lesson.lessonId }); complete.disabled = true; complete.textContent = 'เรียนจบแล้ว'; label.textContent = lesson.title + ' (เรียนจบแล้ว)'; } catch (error) { status.textContent = error.message; } }); lessonNode.appendChild(complete); section.appendChild(lessonNode); }); units.appendChild(section); }); status.textContent = data.units.length ? '' : 'รายวิชานี้ยังไม่มีหน่วยที่เผยแพร่ กรุณาให้ผู้ดูแลเพิ่มและเผยแพร่หน่วยกับบทเรียน'; } catch (error) { status.textContent = error.message; } }
  document.querySelector('#back-to-courses').addEventListener('click', function () { outline.hidden = true; courses.hidden = false; });
  (async function () { if (!sessionStorage.getItem('lms_session_token')) return signIn(); try { const data = await call('MY_LEARNING_COURSES', {}); data.courses.forEach(function (course) { courses.appendChild(card(course)); }); status.textContent = data.courses.length ? '' : 'คุณยังไม่ได้ลงทะเบียนรายวิชา'; } catch (error) { if (error.code === 'UNAUTHENTICATED') signIn(); else status.textContent = error.message; } }());
}());
